services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: andinh
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - 'D:\An_Dinh\VOLUMES_DOCKER\postgres:/data/postgres'
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - 'D:\An_Dinh\VOLUMES_DOCKER\pgadmin:/var/lib/pgadmin'
    ports:
      - "5051:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'D:\An_Dinh\VOLUMES_DOCKER\rabbitmq_data:/data'
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  rabbitmq_data: